import { ProcedureFamily } from "./types"

// ── Procedure Families ────────────────────────────────────────────────────────
// A family = the "product" (like Amazon product page).
// Individual procedures = the "variants" (different setups/tuning/approaches).
// Multiple variants hang under one family. Surgeons are assigned to variants.

export const procedureFamilies: ProcedureFamily[] = [

  // ── Orthopaedics ────────────────────────────────────────────────────────────
  { id: "total-hip-replacement",         name: "Total Hip Replacement",                   specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Primary hip arthroplasty replacing femoral head and acetabulum.",         tags: ["THR", "hip replacement", "arthroplasty", "hip"] },
  { id: "total-knee-replacement",        name: "Total Knee Replacement",                  specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Primary tricompartmental knee arthroplasty.",                              tags: ["TKR", "knee replacement", "arthroplasty"] },
  { id: "total-shoulder-arthroplasty",   name: "Total Shoulder Arthroplasty",             specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Anatomic or reverse shoulder replacement.",                                tags: ["TSA", "shoulder replacement", "RTSA", "arthroplasty"] },
  { id: "im-nail-femur",                 name: "IM Nail — Femur",                         specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Intramedullary nailing for femoral shaft or intertrochanteric fractures.", tags: ["IM nail", "femoral nail", "Gamma nail", "TFN", "fracture"] },
  { id: "acl-reconstruction",            name: "ACL Reconstruction",                      specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Arthroscopic anterior cruciate ligament reconstruction.",                  tags: ["ACL", "anterior cruciate", "knee"] },
  { id: "tlif",                          name: "Transforaminal Lumbar Interbody Fusion",   specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Posterior lumbar fusion with interbody cage and pedicle screws.",          tags: ["TLIF", "spine fusion", "lumbar", "PLIF"] },
  { id: "total-ankle-arthroplasty",      name: "Total Ankle Arthroplasty",                specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Total ankle joint replacement.",                                           tags: ["ankle replacement", "TAR", "arthroplasty"] },
  { id: "dynamic-hip-screw",             name: "Dynamic Hip Screw",                       specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Sliding hip screw fixation for intertrochanteric fractures.",              tags: ["DHS", "hip screw", "fracture fixation"] },
  { id: "unicompartmental-knee",         name: "Unicompartmental Knee Replacement",        specialty: "Orthopaedics",      setting: "Operating Theatre",                   description: "Partial knee replacement — medial or lateral compartment.",                tags: ["UKR", "half knee", "unicompartmental", "Oxford"] },

  // ── General Surgery ─────────────────────────────────────────────────────────
  { id: "cholecystectomy",               name: "Cholecystectomy",                         specialty: "General Surgery",   setting: "Operating Theatre",                   description: "Surgical removal of the gallbladder.",                                     tags: ["lap chole", "gallbladder removal", "cholecystectomy"] },
  { id: "appendicectomy",                name: "Appendicectomy",                          specialty: "General Surgery",   setting: "Operating Theatre",                   description: "Surgical removal of the appendix.",                                        tags: ["appendectomy", "appendix removal", "appendicitis"] },
  { id: "inguinal-hernia-repair",        name: "Inguinal Hernia Repair",                  specialty: "General Surgery",   setting: "Operating Theatre",                   description: "Repair of inguinal hernia — open or laparoscopic.",                        tags: ["hernia", "inguinal", "TEP", "TAPP", "Lichtenstein"] },
  { id: "hartmanns-procedure",           name: "Hartmann's Procedure",                    specialty: "General Surgery",   setting: "Operating Theatre",                   description: "Sigmoid colectomy with end colostomy.",                                    tags: ["Hartmann's", "sigmoid colectomy", "colostomy"] },
  { id: "right-hemicolectomy",           name: "Right Hemicolectomy",                     specialty: "General Surgery",   setting: "Operating Theatre",                   description: "Resection of the right colon.",                                            tags: ["hemicolectomy", "right colon", "colectomy"] },
  { id: "anterior-resection",            name: "Anterior Resection",                      specialty: "General Surgery",   setting: "Operating Theatre",                   description: "Resection of the sigmoid or upper rectum.",                                tags: ["anterior resection", "low anterior resection", "LAR", "rectal"] },
  { id: "thyroidectomy",                 name: "Thyroidectomy",                           specialty: "General Surgery",   setting: "Operating Theatre",                   description: "Surgical removal of the thyroid gland — total or hemi.",                   tags: ["thyroid", "thyroidectomy", "hemi-thyroidectomy"] },

  // ── Urology ─────────────────────────────────────────────────────────────────
  { id: "turp",                          name: "Transurethral Resection of Prostate",      specialty: "Urology",           setting: "Operating Theatre",                   description: "Endoscopic resection of prostatic tissue.",                                tags: ["TURP", "prostate", "BPH"] },
  { id: "pcnl",                          name: "Percutaneous Nephrolithotomy",             specialty: "Urology",           setting: "Operating Theatre",                   description: "Percutaneous removal of renal calculi.",                                   tags: ["PCNL", "kidney stones", "nephrolithiasis"] },
  { id: "nephrectomy",                   name: "Nephrectomy",                             specialty: "Urology",           setting: "Operating Theatre",                   description: "Surgical removal of the kidney.",                                          tags: ["nephrectomy", "kidney removal", "radical nephrectomy"] },
  { id: "cystoscopy",                    name: "Cystoscopy",                              specialty: "Urology",           setting: "Operating Theatre",                   description: "Endoscopic examination of the bladder.",                                   tags: ["cystoscopy", "bladder", "bimanual"] },
  { id: "ureteroscopy",                  name: "Ureteroscopy",                            specialty: "Urology",           setting: "Operating Theatre",                   description: "Endoscopic treatment of ureteric or renal calculi.",                       tags: ["ureteroscopy", "URS", "laser", "kidney stones"] },
  { id: "radical-prostatectomy",         name: "Radical Prostatectomy",                   specialty: "Urology",           setting: "Operating Theatre",                   description: "Surgical removal of the prostate gland.",                                  tags: ["prostatectomy", "robotic", "RARP", "prostate cancer"] },

  // ── Gynaecology ─────────────────────────────────────────────────────────────
  { id: "hysterectomy",                  name: "Hysterectomy",                            specialty: "Gynaecology",       setting: "Operating Theatre",                   description: "Surgical removal of the uterus.",                                          tags: ["hysterectomy", "TLH", "TAH", "uterus"] },
  { id: "myomectomy",                    name: "Myomectomy",                              specialty: "Gynaecology",       setting: "Operating Theatre",                   description: "Surgical removal of uterine fibroids.",                                    tags: ["myomectomy", "fibroids", "uterine"] },
  { id: "laparoscopy-dye",               name: "Laparoscopy & Dye",                       specialty: "Gynaecology",       setting: "Operating Theatre",                   description: "Diagnostic laparoscopy with tubal patency assessment.",                    tags: ["laparoscopy", "dye test", "tubal patency", "subfertility"] },
  { id: "lletz",                         name: "LLETZ",                                   specialty: "Gynaecology",       setting: "Operating Theatre",                   description: "Large loop excision of the transformation zone for CIN.",                  tags: ["LLETZ", "LEEP", "CIN", "cervical"] },
  { id: "tension-free-vaginal-tape",     name: "Tension-Free Vaginal Tape",               specialty: "Gynaecology",       setting: "Operating Theatre",                   description: "Mid-urethral sling for stress urinary incontinence.",                      tags: ["TVT", "sling", "incontinence", "urogynaecology"] },

  // ── ENT ─────────────────────────────────────────────────────────────────────
  { id: "tonsillectomy",                 name: "Tonsillectomy",                           specialty: "ENT",               setting: "Operating Theatre",                   description: "Surgical removal of the palatine tonsils.",                                tags: ["tonsils", "tonsillectomy", "adeno-tonsillectomy"] },
  { id: "grommets",                      name: "Grommet Insertion",                       specialty: "ENT",               setting: "Operating Theatre",                   description: "Tympanostomy tube insertion for otitis media with effusion.",              tags: ["grommets", "tympanostomy", "glue ear", "myringotomy"] },
  { id: "septoplasty",                   name: "Septoplasty",                             specialty: "ENT",               setting: "Operating Theatre",                   description: "Correction of deviated nasal septum.",                                     tags: ["septoplasty", "nasal septum", "deviated septum"] },
  { id: "functional-endoscopic-sinus-surgery", name: "Functional Endoscopic Sinus Surgery", specialty: "ENT",            setting: "Operating Theatre",                   description: "Endoscopic sinus surgery for chronic rhinosinusitis.",                     tags: ["FESS", "sinus", "ESS", "rhinosinusitis"] },
  { id: "pinnaplasty",                   name: "Pinnaplasty",                             specialty: "ENT",               setting: "Operating Theatre",                   description: "Otoplasty — correction of prominent ears.",                                tags: ["pinnaplasty", "otoplasty", "ear correction"] },
  { id: "submandibular-gland-excision",  name: "Submandibular Gland Excision",            specialty: "ENT",               setting: "Operating Theatre",                   description: "Excision of the submandibular salivary gland.",                            tags: ["submandibular", "salivary gland", "sialadenitis"] },

  // ── Ophthalmology ───────────────────────────────────────────────────────────
  { id: "cataract-surgery",              name: "Cataract Surgery",                        specialty: "Ophthalmology",     setting: "Operating Theatre",                   description: "Phacoemulsification with intraocular lens implantation.",                  tags: ["cataract", "phaco", "IOL", "lens implant"] },
  { id: "trabeculectomy",                name: "Trabeculectomy",                          specialty: "Ophthalmology",     setting: "Operating Theatre",                   description: "Glaucoma filtration surgery creating a drainage bleb.",                    tags: ["trabeculectomy", "glaucoma", "filtration"] },
  { id: "vitrectomy",                    name: "Vitrectomy",                              specialty: "Ophthalmology",     setting: "Operating Theatre",                   description: "Posterior vitreous surgery — PPV.",                                        tags: ["vitrectomy", "PPV", "retina", "vitreoretinal"] },
  { id: "strabismus-repair",             name: "Strabismus Repair",                       specialty: "Ophthalmology",     setting: "Operating Theatre",                   description: "Extraocular muscle surgery for squint correction.",                        tags: ["strabismus", "squint", "EOM", "ocular muscle"] },

  // ── Vascular Surgery ────────────────────────────────────────────────────────
  { id: "carotid-endarterectomy",        name: "Carotid Endarterectomy",                  specialty: "Vascular Surgery",  setting: "Operating Theatre",                   description: "Removal of atherosclerotic plaque from the carotid artery.",               tags: ["CEA", "carotid", "stroke prevention"] },
  { id: "aortic-aneurysm-repair",        name: "Aortic Aneurysm Repair",                  specialty: "Vascular Surgery",  setting: "Operating Theatre",                   description: "Endovascular or open repair of aortic aneurysm.",                          tags: ["EVAR", "AAA", "aortic aneurysm", "endovascular"] },
  { id: "peripheral-bypass",             name: "Peripheral Arterial Bypass",              specialty: "Vascular Surgery",  setting: "Operating Theatre",                   description: "Bypass grafting for peripheral arterial disease.",                         tags: ["fem-pop bypass", "bypass graft", "PAD", "peripheral vascular"] },
  { id: "varicose-vein-treatment",       name: "Varicose Vein Treatment",                 specialty: "Vascular Surgery",  setting: "Operating Theatre",                   description: "Surgical or thermal treatment of varicose veins.",                         tags: ["varicose veins", "EVLA", "phlebectomy", "TEVLAR"] },
  { id: "lower-limb-amputation",         name: "Lower Limb Amputation",                   specialty: "Vascular Surgery",  setting: "Operating Theatre",                   description: "Amputation of the lower limb at various levels.",                          tags: ["amputation", "BKA", "AKA", "below knee", "above knee"] },

  // ── Cardiothoracic Surgery ──────────────────────────────────────────────────
  { id: "coronary-artery-bypass",        name: "Coronary Artery Bypass Grafting",          specialty: "Cardiothoracic",    setting: "Operating Theatre",                   description: "Bypass grafting to revascularise the coronary circulation.",               tags: ["CABG", "bypass", "coronary", "heart surgery"] },
  { id: "aortic-valve-replacement",      name: "Aortic Valve Replacement",                specialty: "Cardiothoracic",    setting: "Operating Theatre",                   description: "Replacement of the aortic valve — mechanical or bioprosthetic.",            tags: ["AVR", "aortic valve", "TAVI", "valve replacement"] },
  { id: "lobectomy",                     name: "Lobectomy",                               specialty: "Cardiothoracic",    setting: "Operating Theatre",                   description: "Surgical removal of a pulmonary lobe.",                                    tags: ["lobectomy", "lung", "VATS", "thoracotomy"] },
  { id: "pneumonectomy",                 name: "Pneumonectomy",                           specialty: "Cardiothoracic",    setting: "Operating Theatre",                   description: "Surgical removal of an entire lung.",                                      tags: ["pneumonectomy", "lung resection"] },
  { id: "thoracic-drainage",             name: "Thoracic Drainage",                       specialty: "Cardiothoracic",    setting: "Operating Theatre",                   description: "Surgical drainage of pleural or pericardial collections.",                  tags: ["thoracic drain", "pleural effusion", "empyema"] },

  // ── Neurosurgery ────────────────────────────────────────────────────────────
  { id: "craniotomy",                    name: "Craniotomy",                              specialty: "Neurosurgery",      setting: "Operating Theatre",                   description: "Surgical opening of the skull for intracranial access.",                   tags: ["craniotomy", "brain surgery", "tumour", "neurosurgery"] },
  { id: "burr-hole-drainage",            name: "Burr Hole Drainage",                      specialty: "Neurosurgery",      setting: "Operating Theatre",                   description: "Burr hole insertion to drain intracranial collections.",                   tags: ["burr hole", "haematoma", "CSDH", "subdural"] },
  { id: "vp-shunt",                      name: "VP Shunt",                                specialty: "Neurosurgery",      setting: "Operating Theatre",                   description: "Ventriculoperitoneal shunt for hydrocephalus.",                            tags: ["VP shunt", "hydrocephalus", "shunt"] },
  { id: "lumbar-discectomy",             name: "Lumbar Discectomy",                       specialty: "Neurosurgery",      setting: "Operating Theatre",                   description: "Surgical decompression for lumbar disc herniation.",                       tags: ["discectomy", "disc", "lumbar", "sciatica", "microdiscectomy"] },

  // ── Plastics & Reconstructive ───────────────────────────────────────────────
  { id: "skin-graft",                    name: "Skin Graft",                              specialty: "Plastics",          setting: "Operating Theatre",                   description: "Split-skin or full-thickness graft to cover skin defect.",                 tags: ["skin graft", "SSG", "FTG", "STSG"] },
  { id: "breast-reconstruction",         name: "Breast Reconstruction",                   specialty: "Plastics",          setting: "Operating Theatre",                   description: "Reconstructive surgery following mastectomy.",                              tags: ["DIEP flap", "breast reconstruction", "mastectomy", "flap"] },
  { id: "carpal-tunnel-release",         name: "Carpal Tunnel Release",                   specialty: "Plastics",          setting: "Operating Theatre",                   description: "Surgical decompression of the median nerve at the wrist.",                 tags: ["carpal tunnel", "CTR", "median nerve", "CTS"] },
  { id: "dupuytren-surgery",             name: "Dupuytren's Surgery",                     specialty: "Plastics",          setting: "Operating Theatre",                   description: "Fasciectomy or fasciotomy for Dupuytren's contracture.",                   tags: ["Dupuytren's", "fasciectomy", "contracture", "palmar"] },

  // ── Endoscopy Suite ─────────────────────────────────────────────────────────
  { id: "upper-gi-endoscopy",            name: "Upper GI Endoscopy",                      specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "Diagnostic or therapeutic gastroscopy.",                                   tags: ["OGD", "gastroscopy", "endoscopy", "upper GI"] },
  { id: "colonoscopy",                   name: "Colonoscopy",                             specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "Endoscopic examination of the large bowel.",                               tags: ["colonoscopy", "bowel", "colon", "polyp"] },
  { id: "ercp",                          name: "ERCP",                                    specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "Endoscopic retrograde cholangiopancreatography.",                          tags: ["ERCP", "bile duct", "pancreas", "stones"] },
  { id: "endoscopic-ultrasound",         name: "Endoscopic Ultrasound",                   specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "EUS for staging, biopsy and drainage.",                                    tags: ["EUS", "endoscopic ultrasound", "FNA", "staging"] },
  { id: "capsule-endoscopy",             name: "Capsule Endoscopy",                       specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "Wireless capsule imaging of the small bowel.",                             tags: ["capsule endoscopy", "PillCam", "small bowel"] },
  { id: "flexible-sigmoidoscopy",        name: "Flexible Sigmoidoscopy",                  specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "Endoscopic examination of the rectum and sigmoid.",                        tags: ["flexible sig", "sigmoidoscopy", "rectum"] },
  { id: "enteroscopy",                   name: "Enteroscopy",                             specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "Deep small bowel endoscopy.",                                              tags: ["enteroscopy", "push enteroscopy", "small bowel"] },
  { id: "argon-plasma-coagulation",      name: "Argon Plasma Coagulation",                specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "APC for GI haemostasis or tissue ablation.",                               tags: ["APC", "argon plasma", "haemostasis"] },
  { id: "band-ligation",                 name: "Band Ligation",                           specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "Endoscopic band ligation of varices or haemorrhoids.",                     tags: ["band ligation", "varices", "haemorrhoids", "banding"] },
  { id: "bronchoscopy",                  name: "Bronchoscopy",                            specialty: "Respiratory",       setting: "Endoscopy Suite",                     description: "Endoscopic airway examination — rigid or flexible.",                        tags: ["bronchoscopy", "airway", "BAL", "biopsy"] },
  { id: "endobronchial-biopsy",          name: "Endobronchial Biopsy",                    specialty: "Respiratory",       setting: "Endoscopy Suite",                     description: "Endobronchial biopsy and sampling.",                                       tags: ["endobronchial", "EBUS", "biopsy"] },
  { id: "endoscopic-submucosal-dissection", name: "Endoscopic Submucosal Dissection",     specialty: "Gastroenterology",  setting: "Endoscopy Suite",                     description: "ESD for en bloc resection of GI lesions.",                                 tags: ["ESD", "submucosal dissection", "EMR"] },

  // ── Interventional Radiology / Cath Lab ─────────────────────────────────────
  { id: "coronary-angiography",          name: "Coronary Angiography",                    specialty: "Cardiology",        setting: "Interventional Radiology / Cath Lab",  description: "Invasive coronary artery imaging.",                                        tags: ["angiogram", "coronary angiogram", "catheter", "PCI"] },
  { id: "pacemaker-insertion",           name: "Pacemaker Insertion",                     specialty: "Cardiology",        setting: "Interventional Radiology / Cath Lab",  description: "Permanent pacemaker implantation.",                                        tags: ["pacemaker", "PPM", "ICD", "CRT", "electrophysiology"] },
  { id: "uterine-fibroid-embolisation",  name: "Uterine Fibroid Embolisation",            specialty: "Interventional Radiology", setting: "Interventional Radiology / Cath Lab", description: "UAE for symptomatic uterine fibroids.",                              tags: ["UFE", "UAE", "fibroid", "embolisation"] },
  { id: "hepatic-embolisation",          name: "Hepatic Embolisation",                    specialty: "Interventional Radiology", setting: "Interventional Radiology / Cath Lab", description: "Transarterial embolisation of hepatic lesions or bleeding.",           tags: ["TACE", "hepatic", "embolisation", "liver"] },
  { id: "neuroangiography",              name: "Neuroangiography",                        specialty: "Neuroradiology",    setting: "Interventional Radiology / Cath Lab",  description: "Cerebral angiography and neurointerventional procedures.",                  tags: ["neuro angio", "cerebral angiogram", "coiling", "aneurysm"] },

  // ── ICU ─────────────────────────────────────────────────────────────────────
  { id: "central-line-insertion",        name: "Central Line Insertion",                  specialty: "Critical Care",     setting: "Intensive Care Unit",                  description: "Central venous catheter placement.",                                       tags: ["central line", "CVC", "subclavian", "jugular", "femoral"] },
  { id: "arterial-line-insertion",       name: "Arterial Line Insertion",                 specialty: "Critical Care",     setting: "Intensive Care Unit",                  description: "Invasive arterial pressure monitoring.",                                   tags: ["arterial line", "A-line", "radial", "femoral"] },
  { id: "tracheostomy",                  name: "Tracheostomy",                            specialty: "Critical Care",     setting: "Intensive Care Unit",                  description: "Percutaneous or surgical tracheostomy.",                                   tags: ["tracheostomy", "trache", "percutaneous", "airway"] },

  // ── Emergency Department ────────────────────────────────────────────────────
  { id: "intubation",                    name: "Rapid Sequence Intubation",               specialty: "Emergency Medicine", setting: "Emergency Department",                description: "RSI for emergency airway management.",                                     tags: ["RSI", "intubation", "airway", "ETT", "emergency"] },
  { id: "chest-drain-insertion",         name: "Chest Drain Insertion",                   specialty: "Emergency Medicine", setting: "Emergency Department",                description: "Pleural drain via Seldinger technique.",                                   tags: ["chest drain", "intercostal", "pneumothorax", "effusion"] },
  { id: "dc-cardioversion",              name: "DC Cardioversion",                        specialty: "Cardiology",        setting: "Emergency Department",                 description: "Synchronised electrical cardioversion.",                                   tags: ["DCCV", "cardioversion", "AF", "arrhythmia", "shock"] },
  { id: "lumbar-puncture",               name: "Lumbar Puncture",                         specialty: "Neurology",         setting: "Emergency Department",                 description: "CSF sampling via lumbar spinal access.",                                   tags: ["LP", "lumbar puncture", "spinal tap", "CSF", "meningitis"] },

  // ── Ward ────────────────────────────────────────────────────────────────────
  { id: "urinary-catheterisation",       name: "Urinary Catheterisation",                 specialty: "General Nursing",   setting: "Ward",                                 description: "Insertion of urethral catheter.",                                          tags: ["catheter", "urinary catheter", "Foley", "IDC"] },
  { id: "wound-drain-removal",           name: "Wound Drain Removal",                     specialty: "General Nursing",   setting: "Ward",                                 description: "Removal of post-operative wound drain.",                                   tags: ["drain removal", "Redivac", "wound drain"] },
  { id: "wound-closure-removal",         name: "Wound Closure Removal",                   specialty: "General Nursing",   setting: "Ward",                                 description: "Removal of sutures or surgical staples.",                                  tags: ["suture removal", "staple removal", "wound care"] },
  { id: "wound-care",                    name: "Wound Care",                              specialty: "General Nursing",   setting: "Ward",                                 description: "Assessment and management of wound complications.",                         tags: ["wound dehiscence", "wound care", "dressing"] },
  { id: "ng-tube-insertion",             name: "NG Tube Insertion",                       specialty: "General Nursing",   setting: "Ward",                                 description: "Nasogastric tube insertion and confirmation.",                              tags: ["NG tube", "nasogastric", "feeding tube"] },
  { id: "blood-product-administration",  name: "Blood Product Administration",            specialty: "General Nursing",   setting: "Ward",                                 description: "Safe administration of blood and blood products.",                          tags: ["blood transfusion", "FFP", "platelets", "blood products"] },
  { id: "subcutaneous-infusion",         name: "Subcutaneous Infusion",                   specialty: "General Nursing",   setting: "Ward",                                 description: "Hypodermoclysis / subcutaneous fluid or drug infusion.",                    tags: ["subcutaneous", "hypodermoclysis", "syringe driver"] },

  // ── Outpatient / Clinic ─────────────────────────────────────────────────────
  { id: "skin-lesion-excision",          name: "Skin Lesion Excision",                    specialty: "Dermatology",       setting: "Outpatient / Clinic",                  description: "Excision of skin lesions under local anaesthetic.",                        tags: ["skin excision", "lesion removal", "BCC", "melanoma"] },
  { id: "joint-injection",               name: "Joint Injection",                         specialty: "Rheumatology",      setting: "Outpatient / Clinic",                  description: "Intra-articular steroid or hyaluronic acid injection.",                     tags: ["joint injection", "steroid", "corticosteroid", "aspiration"] },
  { id: "cryotherapy",                   name: "Cryotherapy",                             specialty: "Dermatology",       setting: "Outpatient / Clinic",                  description: "Liquid nitrogen cryotherapy for skin lesions.",                             tags: ["cryotherapy", "liquid nitrogen", "warts", "AK"] },
  { id: "incision-drainage",             name: "Incision & Drainage",                     specialty: "General Surgery",   setting: "Outpatient / Clinic",                  description: "I&D of cutaneous abscess.",                                                tags: ["I&D", "abscess", "incision and drainage"] },
  { id: "iud-insertion",                 name: "Intrauterine Device Insertion",            specialty: "Gynaecology",       setting: "Outpatient / Clinic",                  description: "Insertion of IUD or IUS (coil).",                                          tags: ["IUD", "IUS", "coil", "Mirena", "contraception"] },
  { id: "colposcopy",                    name: "Colposcopy",                              specialty: "Gynaecology",       setting: "Outpatient / Clinic",                  description: "Colposcopic examination with directed biopsy.",                             tags: ["colposcopy", "cervical", "punch biopsy", "CIN"] },
]

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getFamilyById(id: string): ProcedureFamily | undefined {
  return procedureFamilies.find((f) => f.id === id)
}

export function getFamiliesBySetting(setting: string): ProcedureFamily[] {
  return procedureFamilies.filter((f) => f.setting === setting)
}

export function getFamiliesBySpecialty(specialty: string): ProcedureFamily[] {
  return procedureFamilies.filter((f) => f.specialty === specialty)
}
